SBOM workflow
duosecurity/duo_client_python pull request #225
Opened 2023-06-27 20:53 UTC by jeffreyparker

## Description
Add automatic SBOM generation to releases generated by github actions.
This will eventually be added to many repos, so the SBOM conversion is separated into a separate workflow which can be reused by other repos.

## Motivation and Context
Improved transparency on dependency versions and licenses.

## How Has This Been Tested?
This is a bit tricky. The majority of the action has been tested by creating releases on forks https://github.com/jeffreyparker/duo_client_python/actions/runs/5391813505 , but a full end-to-end test isn't possible until a real release is created.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2023-06-27 20:59 UTC, mbish requested changes

2023-06-27 20:59 UTC, mbish commented on scripts/make-sbom.sh
> +cyclonedx-py --e --format json -o cyclonedx-sbom.json
this line should be removed from the conversion script. Also this should probably be renamed to something like "convert-sbom.sh"

2023-06-28 15:10 UTC, AaronAtDuo commented on .github/workflows/sbom-convert.yml
> +          wget https://github.com/CycloneDX/cyclonedx-cli/releases/download/v0.24.2/cyclonedx-linux-x64
is this just the contents of the script below?  is it possible to just run that script?

2023-06-28 16:24 UTC, jeffreyparker commented
Closing this PR in favor of https://github.com/duosecurity/duo_client_python/pull/226 , which uses a composite action instead of a separate workflow. This drastically simplifies calling it, with no need for artifacts.

2023-06-28 16:24 UTC, closed without merging